# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "simple lol"
  lane :test do
   scan(
	scheme: SimpleTest,
	clean: true,
	only_testing: "SimpleTest/SimpleTestTests", 
	xcargs: "-configuration Debug",
	destination: "platform=iOS Simulator,OS=16.2,name=iPhone 14")
  end
end
